version: "3"

services:
    # nginx
    nginx:
        container_name: nginx
        build: ./docker/nginx
        volumes:
            - .:/var/www/html
            - ./docker/nginx/conf.d:/etc/nginx/conf.d
        links:
            - app
        ports:
            - 8000:80
        working_dir: /var/www/html
        depends_on:
            - app
        networks:
            - laravel

    # php
    app:
        container_name: app
        build: ./docker/php
        links:
            - mysql
            - redis
            # - mailhog
        volumes:
            - .:/var/www/html
        working_dir: /var/www/html
        environment:
            - REDIS_HOST=redis
            - DB_HOST=mysql
            - MAIL_HOST=mailhog
            - MAIL_PORT=1025
            - MAIL_DRIVER=smtp
        depends_on:
            - mysql
            - redis
        networks:
            - laravel

    # supervisor
    supervisor:
        container_name: supervisor
        build: ./docker/supervisor
        volumes:
            - .:/var/www/html
        links:
            - app
        working_dir: /var/www/html
        depends_on:
            - app
        networks:
            - laravel

    # database
    mysql:
        container_name: mysql
        image: mariadb:10.6
        volumes:
            - dbstore:/var/lib/mysql
        ports:
            - 3307:3306
        command: --default-authentication-plugin=mysql_native_password
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: "${DB_PASSWORD}"
            MYSQL_DATABASE: "${DB_DATABASE}"
            MYSQL_USER: "${DB_USERNAME}"
            MYSQL_PASSWORD: "${DB_PASSWORD}"
            MYSQL_ALLOW_EMPTY_PASSWORD: 1
        networks:
            - laravel
        healthcheck:
            test: ["CMD", "mysqladmin", "ping", "-p${DB_PASSWORD}"]
            retries: 3
            timeout: 5s

    # redis
    redis:
        image: "redis:alpine"
        ports:
            - "6378:6379"
        volumes:
            - "redistore:/data"
        networks:
            - laravel
        healthcheck:
            test: ["CMD", "redis-cli", "ping"]
            retries: 3
            timeout: 5s

    # mailhog
    mailhog:
        container_name: mailhog
        image: mailhog/mailhog
        ports:
            - 1025:1025
            - 6082:8025
        networks:
            - laravel

networks:
    laravel:
        driver: bridge
volumes:
    dbstore:
        driver: local
    redistore:
        driver: local
